title: Denis Cappellin
author: ''
description: >- # this means to ignore newlines until "baseurl:"
  Mi diverto, lavoro e faccio "cose"
baseurl: "" # the subpath of your site, e.g. /blog
url: https://denis.cappell.in

# Social
mastodon:
  - { username: dcappellin, instance: mastodon.uno }
peertube: 
  - { username: dcappellin, instance: peertube.uno }
linkedin_username: deniscappellin
komoot_username: "1971346940863"
telegram_channel: dcappellin

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/